# Generated by Django 4.2.2 on 2023-06-08 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('desc', models.TextField(max_length=300)),
                ('notes', models.TextField(max_length=300)),
                ('move_date', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=200)),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.move')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('care', models.TextField(max_length=100)),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.move')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.place')),
            ],
        ),
    ]
