# Generated by Django 4.2.2 on 2023-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0004_move_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='purpose',
            field=models.TextField(default='Move', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='origin',
            field=models.BooleanField(default=False),
        ),
    ]
